

EXISTS_CONNECTOR = "exists"
FORALL_CONNECTOR = "forall"
NOT_CONNECTOR = "not"
CONJUNCTION_CONNECTOR = 'conjunction'
DISJUNCTION_CONNECTOR = 'disjunction'
NEGATION_CONNECTOR = 'not'
SUBCONCEPTOF_CONNECTOR = 'subConceptOf'
EQCONCEPT_CONNECTOR = 'eqConceptTo'

INSTANCEOF_CONNECTOR = 'instanceOf'

